import type { Track, Genre } from './types'

export const DEFAULT_CATALOG: Track[] = [
  { id: '1', title: 'Bohemian Rhapsody', artist: 'Queen', genres: ['Rock'] },
  { id: '2', title: 'Hotel California', artist: 'Eagles', genres: ['Rock'] },
  { id: '3', title: 'Stairway to Heaven', artist: 'Led Zeppelin', genres: ['Rock'] },
  { id: '4', title: 'Smells Like Teen Spirit', artist: 'Nirvana', genres: ['Rock', 'Alternative'] },
  { id: '5', title: 'Back in Black', artist: 'AC/DC', genres: ['Rock'] },
  { id: '6', title: 'Billie Jean', artist: 'Michael Jackson', genres: ['Pop', 'R&B'] },
  { id: '7', title: 'Thriller', artist: 'Michael Jackson', genres: ['Pop'] },
  { id: '8', title: 'Like a Rolling Stone', artist: 'Bob Dylan', genres: ['Folk', 'Rock'] },
  { id: '9', title: 'Imagine', artist: 'John Lennon', genres: ['Pop', 'Rock'] },
  { id: '10', title: 'What a Wonderful World', artist: 'Louis Armstrong', genres: ['Jazz'] },
  { id: '11', title: 'Take Five', artist: 'Dave Brubeck', genres: ['Jazz'] },
  { id: '12', title: 'So What', artist: 'Miles Davis', genres: ['Jazz'] },
  { id: '13', title: 'Around the World', artist: 'Daft Punk', genres: ['Electronic'] },
  { id: '14', title: 'Strobe', artist: 'Deadmau5', genres: ['Electronic'] },
  { id: '15', title: 'Levels', artist: 'Avicii', genres: ['Electronic', 'Pop'] },
  { id: '16', title: 'One More Time', artist: 'Daft Punk', genres: ['Electronic'] },
  { id: '17', title: 'Alright', artist: 'Kendrick Lamar', genres: ['Hip-Hop'] },
  { id: '18', title: 'Juicy', artist: 'The Notorious B.I.G.', genres: ['Hip-Hop'] },
  { id: '19', title: 'Lose Yourself', artist: 'Eminem', genres: ['Hip-Hop'] },
  { id: '20', title: 'HUMBLE.', artist: 'Kendrick Lamar', genres: ['Hip-Hop'] },
  { id: '21', title: 'Für Elise', artist: 'Beethoven', genres: ['Classical'] },
  { id: '22', title: 'Clair de Lune', artist: 'Debussy', genres: ['Classical'] },
  { id: '23', title: 'The Four Seasons: Spring', artist: 'Vivaldi', genres: ['Classical'] },
  { id: '24', title: 'Canon in D', artist: 'Pachelbel', genres: ['Classical'] },
  { id: '25', title: 'Blinding Lights', artist: 'The Weeknd', genres: ['Pop', 'R&B'] },
  { id: '26', title: 'Uptown Funk', artist: 'Bruno Mars', genres: ['Pop', 'Funk'] },
  { id: '27', title: 'Rolling in the Deep', artist: 'Adele', genres: ['Pop', 'Soul'] },
  { id: '28', title: 'Shape of You', artist: 'Ed Sheeran', genres: ['Pop'] },
  { id: '29', title: 'Jolene', artist: 'Dolly Parton', genres: ['Country'] },
  { id: '30', title: 'Ring of Fire', artist: 'Johnny Cash', genres: ['Country'] },
  { id: '31', title: 'The Gambler', artist: 'Kenny Rogers', genres: ['Country'] },
  { id: '32', title: 'Enter Sandman', artist: 'Metallica', genres: ['Metal'] },
  { id: '33', title: 'Master of Puppets', artist: 'Metallica', genres: ['Metal'] },
  { id: '34', title: 'Paranoid', artist: 'Black Sabbath', genres: ['Metal', 'Rock'] },
  { id: '35', title: 'One', artist: 'Metallica', genres: ['Metal'] },
  { id: '36', title: 'No Woman No Cry', artist: 'Bob Marley', genres: ['Reggae'] },
  { id: '37', title: 'Three Little Birds', artist: 'Bob Marley', genres: ['Reggae'] },
  { id: '38', title: 'Redemption Song', artist: 'Bob Marley', genres: ['Reggae', 'Folk'] },
  { id: '39', title: 'Mr. Brightside', artist: 'The Killers', genres: ['Indie', 'Rock'] },
  { id: '40', title: 'Do I Wanna Know?', artist: 'Arctic Monkeys', genres: ['Indie', 'Rock'] },
  { id: '41', title: 'The Less I Know The Better', artist: 'Tame Impala', genres: ['Indie', 'Pop'] },
  { id: '42', title: 'The Thrill Is Gone', artist: 'B.B. King', genres: ['Blues'] },
  { id: '43', title: 'Crossroads', artist: 'Robert Johnson', genres: ['Blues'] },
  { id: '44', title: 'Pride and Joy', artist: 'Stevie Ray Vaughan', genres: ['Blues', 'Rock'] },
  { id: '45', title: 'The Sound of Silence', artist: 'Simon & Garfunkel', genres: ['Folk'] },
  { id: '46', title: 'Blowin\' in the Wind', artist: 'Bob Dylan', genres: ['Folk'] },
  { id: '47', title: 'Despacito', artist: 'Luis Fonsi', genres: ['Latin', 'Pop'] },
  { id: '48', title: 'Gasolina', artist: 'Daddy Yankee', genres: ['Latin'] },
  { id: '49', title: 'Superstition', artist: 'Stevie Wonder', genres: ['Soul', 'Funk'] },
  { id: '50', title: 'Respect', artist: 'Aretha Franklin', genres: ['Soul'] },
  { id: '51', title: 'A Change Is Gonna Come', artist: 'Sam Cooke', genres: ['Soul'] },
  { id: '52', title: 'Super Freak', artist: 'Rick James', genres: ['Funk'] },
  { id: '53', title: 'Get Up (I Feel Like Being a) Sex Machine', artist: 'James Brown', genres: ['Funk', 'Soul'] },
  { id: '54', title: 'Blitzkrieg Bop', artist: 'Ramones', genres: ['Punk', 'Rock'] },
  { id: '55', title: 'Anarchy in the UK', artist: 'Sex Pistols', genres: ['Punk'] },
  { id: '56', title: 'Weightless', artist: 'Marconi Union', genres: ['Ambient'] },
  { id: '57', title: 'Music for Airports', artist: 'Brian Eno', genres: ['Ambient', 'Electronic'] },
  { id: '58', title: 'Africa', artist: 'Toto', genres: ['Pop Rock', 'Rock'] },
  { id: '59', title: 'Don\'t Stop Believin\'', artist: 'Journey', genres: ['Pop Rock', 'Rock'] },
  { id: '60', title: 'Piano Man', artist: 'Billy Joel', genres: ['Pop Rock'] },
]

export const ALL_GENRES: Genre[] = [
  'Rock', 'Pop', 'Jazz', 'Electronic', 'Hip-Hop',
  'Classical', 'R&B', 'Country', 'Metal', 'Reggae',
  'Indie', 'Blues', 'Folk', 'Latin', 'Soul',
  'Funk', 'Punk', 'Ambient', 'Pop Rock', 'Alternative',
]

export function generateId(): string {
  return `user-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`
}
